[project]
name = "template_project_name"
version = "0.1.0"
description = ""
authors = []
dependencies = ["loguru>=0.7.0", "typer>=0.15.2"]
requires-python = ">=3.12"
readme = "README.md"

[tool.pdm.scripts]
template_project_name = "template_project_name.cli:main"

[project.scripts]
template_project_name = "template_project_name.cli:main"

[dependency-groups]
dev = [
    "tox>=4.25.0",
    "pytest>=8.3.5",
    "ruff>=0.11.6",
    "mypy>=1.15.0",
]
